### ISSUE TITLE
Issues on CSSEGI dataset time series table

### ISSUE THREAD

**Issue by yusufhilmi** [aitahtman/coronavirus-api#1]
CSSEGI repo has been changed and this api no longer works. They said they will no longer support for recovered cases in time series table

**Comment by aitahtman** [comment]
@yusufhilmi  I'm working on changes to use the new files architecture.

**Comment by aitahtman** [comment]
@yusufhilmi I just removed the  variable "recovered" from the result of _\getData_ request.
